### ISSUE TITLE
Change Graph endpoint

### ISSUE THREAD

**Issue by vrde** [TelediskoDAO/pre-draft-mailer#10]
The new endpoint is https://api.neokingdom.org/subgraphs/name/TelediskoDAO/dao

**Comment by sirnicolaz** [comment]
https://github.com/TelediskoDAO/mailer/commit/a815bfb5b4b6f938d0c97883b71fcb0f91039ff1#diff-b1b9719b6eae4103d520f1e902420f5073b5e18a5a47aa73feed71a037557c98R35
